---
- name: TLS | Set list of domains
  set_fact:
    list_domains: >
      {{ list_domains | default([]) }} +
      {% if tls.acme_domains %}
      {{ ['/root/.acme.sh.' + tls.acme_domains[0] |join] }}
      {% else %}
      []
      {% endif %}
    list_delete_subdirectories: >
      {{ list_delete_subdirectories | default([]) }} +
      {% if tls.keylength in ['2048','3072','4096'] and tls.acme_domains %}
      {{ ['/root/.acme.sh.' + tls.acme_domains[0] | join + '/' + tls.acme_domains[0] | join + '_ecc' ] }}{% elif tls.acme_domains %}
      {{ ['/root/.acme.sh.' + tls.acme_domains[0] | join + '/' + tls.acme_domains[0] | join] }}{% else %}
      []
      {% endif %}
  loop: "{{ tls_data }}"
  loop_control:
    loop_var: tls

- name: TLS | Find installed domains
  find:
    paths: "/root"
    patterns: ".acme.sh*"
    hidden: True
    file_type: "directory"
  register: list_domain_directories

- name: TLS | Select name of installed domains
  set_fact:
    list_installed_domains: "{{ list_installed_domains | default([]) }} + [ '{{ item.path }}' ]"
  with_items: "{{ list_domain_directories.files }}"

- name: TLS | show list of existing domains
  debug:
    msg: "Here is the list of domains found on target host: {{ list_installed_domains | default([]) }}"

- name: TLS | show list of domains to install
  debug:
    msg: "Here is the list of domains to install onto target host: {{ list_domains }}"

- name: TLS | show list of domains to deletion
  debug:
    msg: "Here is the list of domains to delete: {{ list_installed_domains | default([]) | difference(list_domains) }}"

- name: TLS | Delete old configs
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ list_installed_domains | default([]) | difference(list_domains) }}"

- name: TLS | Delete old subdirectories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ list_delete_subdirectories }}"

- name: TLS | Delete old crontab entries
  become: yes
  become_user: root
  ansible.builtin.cron:
    name: "TLS update from config directory - {{ item }}"
    state: "absent"
  with_items: "{{ list_installed_domains | default([]) | difference(list_domains) }}"
